// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GodotTypeProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("GodotTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing GodotTypeProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GodotTypeProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "GodotTypeProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing GodotTypeProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
